stages:
    - build
    - deploy
build:
    stage: build
    script:
        - yarn
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_production:
    stage: deploy
    script:
        - echo "Deploying to server"
        - cp -rv build/* /var/www/html/src/
        - echo "Deployed"
    environment:
        name: production
        url: schoolchan.pl
    only:
        - master